import React, { useEffect, useState } from 'react';
import { supabase } from './lib/supabase';

const styles=`#litesms-admin-root{position:fixed;inset:0;z-index:9999;background:#f8fafc;color:#0f172a;display:none;overflow:auto;font-family:inherit}#litesms-admin-root .wrap{max-width:1100px;margin:auto;padding:18px 16px 40px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.head h1{margin:0;font-size:24px}.close,.action{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.action{background:#0f766e;color:#fff}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:14px;margin-bottom:12px}.card small{color:#64748b}.num{display:block;font-size:22px;margin-top:5px}.row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid #e2e8f0}.row:first-child{border-top:0}.muted{color:#64748b;font-size:12px}.error{padding:12px;border-radius:10px;background:#fef2f2;color:#b91c1c}.tabs{display:flex;gap:8px;overflow:auto;margin-bottom:12px}.tab{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:9px 12px;font-weight:700;white-space:nowrap}.tab.on{background:#0f766e;color:#fff;border-color:#0f766e}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:left;padding:9px;border-bottom:1px solid #e2e8f0;white-space:nowrap}.input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:9px;margin:4px 0 8px}.formgrid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px;align-items:end}.notice{padding:10px;border-radius:10px;background:#ecfeff;color:#155e75;margin-bottom:10px}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}.formgrid{grid-template-columns:1fr}.table table{font-size:12px}}`;
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;'}[c]||c));}
function money(v){return `₦${Number(v||0).toLocaleString()}`;}
function mount(){let root=document.getElementById('litesms-admin-root');if(root)return root;const s=document.createElement('style');s.textContent=styles;document.head.appendChild(s);root=document.createElement('div');root.id='litesms-admin-root';root.innerHTML='<div class="wrap"><div class="head"><h1>Admin Dashboard</h1><button class="close">Close</button></div><div id="admin-content"></div></div>';document.body.appendChild(root);root.querySelector('.close').onclick=()=>root.style.display='none';return root;}

function AdminLauncher(){const [view,setView]=useState('overview');const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [selected,setSelected]=useState('');const [adjustAmount,setAdjustAmount]=useState('');const [adjustType,setAdjustType]=useState('credit');const [adjustDescription,setAdjustDescription]=useState('Admin wallet adjustment');const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const initData=window.Telegram?.WebApp?.initData;if(!initData)throw new Error('Open Litesms inside Telegram.');const auth=await supabase.functions.invoke('telegram-auth',{body:{initData}});if(auth.error||auth.data?.error||auth.data?.profile?.role!=='admin')throw new Error('Admin access required');const r=await supabase.functions.invoke('litesms-admin',{body:{initData,action:'dashboard'}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error?.message||'Unable to load admin dashboard');setData(r.data||{});}catch(e){setError(e.message||'Unable to load admin dashboard.')}finally{setLoading(false)}};
 useEffect(()=>{const root=mount();root.style.display='block';load();return()=>{}},[]);
 const adjust=async()=>{if(!selected||!adjustAmount)return;setBusy(true);setError('');try{const initData=window.Telegram?.WebApp?.initData;const r=await supabase.functions.invoke('litesms-admin',{body:{initData,action:'adjust_wallet',profile_id:selected,amount:Number(adjustAmount),type:adjustType,description:adjustDescription}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error?.message||'Wallet adjustment failed');setAdjustAmount('');await load();alert(`Wallet updated. New balance: ${money(r.data.balance)}`);}catch(e){setError(e.message||'Wallet adjustment failed.')}finally{setBusy(false)}};
 const d=data||{},users=Array.isArray(d.users)?d.users:[],wallets=Array.isArray(d.wallets)?d.wallets:[],orders=Array.isArray(d.recentOrders)?d.recentOrders:[],tx=Array.isArray(d.recentTransactions)?d.recentTransactions:[],topups=Array.isArray(d.topups)?d.topups:[];
 const walletMap=new Map(wallets.map(w=>[w.profile_id,w]));const filteredUsers=users.filter(u=>`${u.username||''} ${u.first_name||''} ${u.last_name||''} ${u.telegram_user_id||''}`.toLowerCase().includes(search.toLowerCase()));const filteredOrders=orders.filter(o=>`${o.service||''} ${o.country||''} ${o.status||''} ${o.phone_number||''}`.toLowerCase().includes(search.toLowerCase()));
 let body='';
 if(loading)body='<div class="card">Loading admin data…</div>';else if(error)body=`<div class="error">${esc(error)}</div>`;else if(view==='overview')body=`<div class="grid"><div class="card"><small>Total users</small><strong class="num">${Number(d.stats?.users||0).toLocaleString()}</strong></div><div class="card"><small>Total orders</small><strong class="num">${Number(d.stats?.orders||0).toLocaleString()}</strong></div><div class="card"><small>Sales</small><strong class="num">${money(d.stats?.sales)}</strong></div><div class="card"><small>Profit</small><strong class="num">${money(d.stats?.profit)}</strong></div></div><div class="card"><strong>Provider status</strong><div class="row"><span>5SIM</span><b>Active</b></div><div class="row"><span>SMSPool</span><b>Inactive</b></div></div><div class="card"><strong>Recent orders</strong>${orders.slice(0,10).map(o=>`<div class="row"><span>${esc(o.service)} · ${esc(o.country)}<br><span class="muted">${esc(o.status)} · ${esc(o.phone_number)}</span></span><b>${money(o.retail_price_ngn??o.amount)}</b></div>`).join('')||'<p>No orders yet.</p>'}</div>`;
 else if(view==='users')body=`<div class="card"><input class="input" placeholder="Search users" value="${esc(search)}" id="admin-search"><div class="table"><table><thead><tr><th>User</th><th>Telegram ID</th><th>Role</th><th>Balance</th><th>Created</th></tr></thead><tbody>${filteredUsers.map(u=>{const w=walletMap.get(u.id);return `<tr><td>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||'—')}</td><td>${esc(u.telegram_user_id)}</td><td>${esc(u.role)}</td><td>${money(w?.balance)}</td><td>${esc(new Date(u.created_at).toLocaleDateString())}</td></tr>`}).join('')}</tbody></table></div></div>`;
 else if(view==='orders')body=`<div class="card"><input class="input" placeholder="Search orders" value="${esc(search)}" id="admin-search"><div class="table"><table><thead><tr><th>Service</th><th>Country</th><th>Number</th><th>Status</th><th>Retail</th><th>Cost</th><th>Profit</th></tr></thead><tbody>${filteredOrders.map(o=>`<tr><td>${esc(o.service)}</td><td>${esc(o.country)}</td><td>${esc(o.phone_number)}</td><td>${esc(o.status)}</td><td>${money(o.retail_price_ngn)}</td><td>${money(o.provider_cost_ngn)}</td><td>${money(o.profit_ngn)}</td></tr>`).join('')}</tbody></table></div></div>`;
 else if(view==='transactions')body=`<div class="card"><strong>Wallet transactions</strong><div class="table"><table><thead><tr><th>Type</th><th>Amount</th><th>Reference</th><th>Description</th><th>Date</th></tr></thead><tbody>${tx.map(t=>`<tr><td>${esc(t.type)}</td><td>${money(t.amount)}</td><td>${esc(t.reference)}</td><td>${esc(t.description)}</td><td>${esc(new Date(t.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="5">No transactions.</td></tr>'}</tbody></table></div></div><div class="card"><strong>Deposits</strong>${topups.slice(0,30).map(t=>`<div class="row"><span>${esc(t.reference)}<br><span class="muted">${esc(t.status)} · ${esc(new Date(t.created_at).toLocaleString())}</span></span><b>${money(t.amount)}</b></div>`).join('')||'<p>No deposits.</p>'}</div>`;
 else if(view==='wallet')body=`<div class="card"><div class="notice">Manual wallet changes are recorded as admin transactions and cannot make a wallet negative.</div><label>User</label><select class="input" id="admin-user"><option value="">Select user</option>${users.map(u=>`<option value="${u.id}" ${selected===u.id?'selected':''}>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||u.telegram_user_id)} — ${money(walletMap.get(u.id)?.balance)}</option>`).join('')}</select><div class="formgrid"><div><label>Amount</label><input class="input" id="admin-amount" placeholder="1000" value="${esc(adjustAmount)}"></div><div><label>Action</label><select class="input" id="admin-type"><option value="credit" ${adjustType==='credit'?'selected':''}>Credit</option><option value="debit" ${adjustType==='debit'?'selected':''}>Debit</option></select></div><div><label>Description</label><input class="input" id="admin-description" value="${esc(adjustDescription)}"></div></div><button class="action" id="admin-adjust" ${busy?'disabled':''}>${busy?'Saving…':'Apply adjustment'}</button></div>`;
 const content=mount().querySelector('#admin-content');content.innerHTML=`<div class="tabs">${['overview','users','orders','transactions','wallet'].map(v=>`<button class="tab ${view===v?'on':''}" data-view="${v}">${v==='overview'?'Overview':v==='wallet'?'Wallet controls':v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div>${body}`;
 content.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);setSearch('');});const q=content.querySelector('#admin-search');if(q)q.oninput=e=>setSearch(e.target.value);const us=content.querySelector('#admin-user');if(us)us.onchange=e=>setSelected(e.target.value);const am=content.querySelector('#admin-amount');if(am)am.oninput=e=>setAdjustAmount(e.target.value);const ty=content.querySelector('#admin-type');if(ty)ty.onchange=e=>setAdjustType(e.target.value);const de=content.querySelector('#admin-description');if(de)de.oninput=e=>setAdjustDescription(e.target.value);const btn=content.querySelector('#admin-adjust');if(btn)btn.onclick=adjust;
 return null;}
export function renderAdminDashboard(){return React.createElement(AdminLauncher);}
