import React, { useEffect, useState } from 'react';
import { supabase } from './lib/supabase';

const styles=`#litesms-admin-root{position:fixed;inset:0;z-index:9999;background:#f8fafc;color:#0f172a;display:none;overflow:auto;font-family:inherit}#litesms-admin-root .wrap{max-width:1100px;margin:auto;padding:18px 16px 40px}.head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.head h1{margin:0;font-size:24px}.close{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:14px;margin-bottom:12px}.card small{color:#64748b}.num{display:block;font-size:22px;margin-top:5px}.row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid #e2e8f0}.row:first-child{border-top:0}.muted{color:#64748b;font-size:12px}.error{padding:12px;border-radius:10px;background:#fef2f2;color:#b91c1c}.tabs{display:flex;gap:8px;overflow:auto;margin-bottom:12px}.tab{border:1px solid #cbd5e1;background:#fff;border-radius:10px;padding:9px 12px;font-weight:700;white-space:nowrap}.tab.on{background:#0f766e;color:#fff;border-color:#0f766e}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:left;padding:9px;border-bottom:1px solid #e2e8f0;white-space:nowrap}.input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:9px;margin:4px 0 8px;background:#fff}.filters{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px;align-items:center}.select{appearance:auto;min-height:40px}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#e2e8f0;font-size:11px;font-weight:800}.bad{background:#fee2e2;color:#991b1b}.good{background:#dcfce7;color:#166534}.notice{padding:10px;border-radius:10px;background:#ecfeff;color:#155e75;margin-bottom:10px}@media(max-width:700px){.grid{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr}.table table{font-size:12px}}`;
function esc(v){return String(v??'').replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;'}[c]||c));}
function money(v){return `₦${Number(v||0).toLocaleString()}`;}
function statusBadge(v){const s=String(v||'').toLowerCase();const good=['completed','successful','active','received'].includes(s);return `<span class="badge ${good?'good':s==='failed'||s==='cancelled'?'bad':''}">${esc(v||'—')}</span>`;}
function mount(){let root=document.getElementById('litesms-admin-root');if(root)return root;const s=document.createElement('style');s.textContent=styles;document.head.appendChild(s);root=document.createElement('div');root.id='litesms-admin-root';root.innerHTML='<div class="wrap"><div class="head"><h1>Admin Dashboard</h1><button class="close">Close</button></div><div id="admin-content"></div></div>';document.body.appendChild(root);root.querySelector('.close').onclick=()=>root.style.display='none';return root;}

function AdminLauncher(){const [view,setView]=useState('overview');const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [orderStatus,setOrderStatus]=useState('all');const [txType,setTxType]=useState('all');const [topupStatus,setTopupStatus]=useState('all');
 const load=async()=>{setLoading(true);setError('');try{const initData=window.Telegram?.WebApp?.initData;if(!initData)throw new Error('Open Litesms inside Telegram.');const r=await supabase.functions.invoke('litesms-admin',{body:{initData,action:'dashboard'}});if(r.error||r.data?.error)throw new Error(r.data?.error||r.error?.message||'Unable to load admin dashboard');setData(r.data||{});}catch(e){setError(e.message||'Unable to load admin dashboard.')}finally{setLoading(false)}};
 useEffect(()=>{const root=mount();root.style.display='block';load();return()=>{}},[]);
 const d=data||{},users=Array.isArray(d.users)?d.users:[],wallets=Array.isArray(d.wallets)?d.wallets:[],orders=Array.isArray(d.recentOrders)?d.recentOrders:[],tx=Array.isArray(d.recentTransactions)?d.recentTransactions:[],topups=Array.isArray(d.topups)?d.topups:[];
 const walletMap=new Map(wallets.map(w=>[w.profile_id,w]));const q=search.toLowerCase();const filteredUsers=users.filter(u=>`${u.username||''} ${u.first_name||''} ${u.last_name||''} ${u.telegram_user_id||''}`.toLowerCase().includes(q));const filteredOrders=orders.filter(o=>(orderStatus==='all'||String(o.status||'').toLowerCase()===orderStatus)&&`${o.service||''} ${o.country||''} ${o.status||''} ${o.phone_number||''}`.toLowerCase().includes(q));const filteredTx=tx.filter(t=>(txType==='all'||String(t.type||'').toLowerCase()===txType)&&`${t.type||''} ${t.reference||''} ${t.description||''} ${t.profile_id||''}`.toLowerCase().includes(q));const filteredTopups=topups.filter(t=>(topupStatus==='all'||String(t.status||'').toLowerCase()===topupStatus)&&`${t.reference||''} ${t.status||''} ${t.profile_id||''}`.toLowerCase().includes(q));
 const failedOrders=orders.filter(o=>['failed','cancelled','expired'].includes(String(o.status||'').toLowerCase())).length;const completedOrders=orders.filter(o=>String(o.status||'').toLowerCase()==='completed').length;
 let body='';
 if(loading)body='<div class="card">Loading admin data…</div>';else if(error)body=`<div class="error">${esc(error)}</div>`;else if(view==='overview')body=`<div class="grid"><div class="card"><small>Total users</small><strong class="num">${Number(d.stats?.users||0).toLocaleString()}</strong></div><div class="card"><small>Total orders</small><strong class="num">${Number(d.stats?.orders||0).toLocaleString()}</strong></div><div class="card"><small>Sales</small><strong class="num">${money(d.stats?.sales)}</strong></div><div class="card"><small>Profit</small><strong class="num">${money(d.stats?.profit)}</strong></div></div><div class="grid"><div class="card"><small>Completed orders</small><strong class="num">${completedOrders}</strong></div><div class="card"><small>Failed/cancelled</small><strong class="num">${failedOrders}</strong></div><div class="card"><small>Successful deposits</small><strong class="num">${money(d.stats?.successfulTopups)}</strong></div><div class="card"><small>Transactions</small><strong class="num">${Number(d.stats?.transactions||0).toLocaleString()}</strong></div></div><div class="card"><strong>Provider status</strong><div class="row"><span>5SIM</span><b class="good">Active</b></div><div class="row"><span>SMSPool</span><b>Inactive</b></div></div><div class="card"><strong>Recent orders</strong>${orders.slice(0,10).map(o=>`<div class="row"><span>${esc(o.service)} · ${esc(o.country)}<br><span class="muted">${statusBadge(o.status)} · ${esc(o.phone_number)}</span></span><b>${money(o.retail_price_ngn??o.amount)}</b></div>`).join('')||'<p>No orders yet.</p>'}</div>`;
 else if(view==='users')body=`<div class="card"><input class="input" placeholder="Search by name, username or Telegram ID" value="${esc(search)}" id="admin-search"><div class="table"><table><thead><tr><th>User</th><th>Telegram ID</th><th>Role</th><th>Balance</th><th>Created</th></tr></thead><tbody>${filteredUsers.map(u=>{const w=walletMap.get(u.id);return `<tr><td>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||'—')}</td><td>${esc(u.telegram_user_id)}</td><td>${esc(u.role)}</td><td>${money(w?.balance)}</td><td>${esc(new Date(u.created_at).toLocaleDateString())}</td></tr>`}).join('')||'<tr><td colspan="5">No matching users.</td></tr>'}</tbody></table></div></div>`;
 else if(view==='orders')body=`<div class="card"><div class="filters"><input class="input" placeholder="Search service, country, number or status" value="${esc(search)}" id="admin-search"><select class="input select" id="order-status"><option value="all">All statuses</option><option value="pending" ${orderStatus==='pending'?'selected':''}>Pending</option><option value="active" ${orderStatus==='active'?'selected':''}>Active</option><option value="completed" ${orderStatus==='completed'?'selected':''}>Completed</option><option value="failed" ${orderStatus==='failed'?'selected':''}>Failed</option><option value="cancelled" ${orderStatus==='cancelled'?'selected':''}>Cancelled</option><option value="expired" ${orderStatus==='expired'?'selected':''}>Expired</option></select><button class="close" id="order-clear">Clear filters</button></div><div class="table"><table><thead><tr><th>Service</th><th>Country</th><th>Number</th><th>Status</th><th>Retail</th><th>Cost</th><th>Profit</th><th>Date</th></tr></thead><tbody>${filteredOrders.map(o=>`<tr><td>${esc(o.service)}</td><td>${esc(o.country)}</td><td>${esc(o.phone_number)}</td><td>${statusBadge(o.status)}</td><td>${money(o.retail_price_ngn)}</td><td>${money(o.provider_cost_ngn)}</td><td>${money(o.profit_ngn)}</td><td>${esc(new Date(o.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="8">No matching orders.</td></tr>'}</tbody></table></div></div>`;
 else if(view==='transactions')body=`<div class="card"><div class="filters"><input class="input" placeholder="Search transactions/deposits" value="${esc(search)}" id="admin-search"><select class="input select" id="tx-type"><option value="all">All transaction types</option><option value="deposit" ${txType==='deposit'?'selected':''}>Deposit</option><option value="purchase" ${txType==='purchase'?'selected':''}>Purchase</option><option value="refund" ${txType==='refund'?'selected':''}>Refund</option><option value="admin_credit" ${txType==='admin_credit'?'selected':''}>Admin credit</option><option value="admin_debit" ${txType==='admin_debit'?'selected':''}>Admin debit</option></select><select class="input select" id="topup-status"><option value="all">All deposit statuses</option><option value="pending" ${topupStatus==='pending'?'selected':''}>Pending</option><option value="successful" ${topupStatus==='successful'?'selected':''}>Successful</option><option value="completed" ${topupStatus==='completed'?'selected':''}>Completed</option><option value="failed" ${topupStatus==='failed'?'selected':''}>Failed</option><option value="cancelled" ${topupStatus==='cancelled'?'selected':''}>Cancelled</option></select></div><strong>Wallet transactions</strong><div class="table"><table><thead><tr><th>Type</th><th>Amount</th><th>Reference</th><th>Description</th><th>Date</th></tr></thead><tbody>${filteredTx.map(t=>`<tr><td>${esc(t.type)}</td><td>${money(t.amount)}</td><td>${esc(t.reference)}</td><td>${esc(t.description)}</td><td>${esc(new Date(t.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="5">No matching transactions.</td></tr>'}</tbody></table></div></div><div class="card"><strong>Deposits</strong><div class="table"><table><thead><tr><th>Reference</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>${filteredTopups.map(t=>`<tr><td>${esc(t.reference)}</td><td>${money(t.amount)}</td><td>${statusBadge(t.status)}</td><td>${esc(new Date(t.created_at).toLocaleString())}</td></tr>`).join('')||'<tr><td colspan="4">No matching deposits.</td></tr>'}</tbody></table></div></div>`;
 const content=mount().querySelector('#admin-content');content.innerHTML=`<div class="tabs">${['overview','users','orders','transactions'].map(v=>`<button class="tab ${view===v?'on':''}" data-view="${v}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div>${body}`;
 content.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);setSearch('');});const qel=content.querySelector('#admin-search');if(qel)qel.oninput=e=>setSearch(e.target.value);const os=content.querySelector('#order-status');if(os)os.onchange=e=>setOrderStatus(e.target.value);const ts=content.querySelector('#tx-type');if(ts)ts.onchange=e=>setTxType(e.target.value);const ds=content.querySelector('#topup-status');if(ds)ds.onchange=e=>setTopupStatus(e.target.value);const clear=content.querySelector('#order-clear');if(clear)clear.onclick=()=>{setSearch('');setOrderStatus('all');};
 return null;}
export function renderAdminDashboard(){return React.createElement(AdminLauncher);}
