import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './lib/supabase';
import './styles.css';
function App(){
 const [profile,setProfile]=useState(null),[wallet,setWallet]=useState(null),[orders,setOrders]=useState([]);const [authStatus,setAuthStatus]=useState('Connecting…'),[dbStatus,setDbStatus]=useState('checking'),[tab,setTab]=useState('home');const [country,setCountry]=useState('US'),[service,setService]=useState('Discord'),[buying,setBuying]=useState(false),[message,setMessage]=useState('');const [amount,setAmount]=useState('5000'),[depositing,setDepositing]=useState(false),[paymentUrl,setPaymentUrl]=useState('');const [providerStatus,setProviderStatus]=useState('checking'),[countries,setCountries]=useState([]),[services,setServices]=useState([]);
 const loadData=async(id)=>{if(!id||!supabase)return;const t=window.Telegram?.WebApp;if(t?.initData){const {data,error}=await supabase.functions.invoke('litesms-user-data',{body:{initData:t.initData}});if(!error&&!data?.error){setWallet(data.wallet||null);setOrders(data.orders||[]);return}}setWallet(null);setOrders([])};
 useEffect(()=>{const t=window.Telegram?.WebApp;if(!t)return setAuthStatus('Open inside Telegram');t.ready();t.expand();if(!t.initData)return setAuthStatus('Open inside Telegram');if(!supabase)return setAuthStatus('Supabase configuration missing');(async()=>{try{const {data,error}=await supabase.functions.invoke('telegram-auth',{body:{initData:t.initData}});if(error||data?.error)return setAuthStatus('Authentication unavailable');setProfile(data.profile);setAuthStatus('Connected');await loadData(data.profile.id)}catch{setAuthStatus('Authentication unavailable')}})()},[]);
 useEffect(()=>{if(!supabase)return setDbStatus('offline');supabase.from('providers').select('id').limit(1).then(({error})=>setDbStatus(error?'offline':'connected')).catch(()=>setDbStatus('offline'))},[]);
 useEffect(()=>{(async()=>{try{const [c,s,b]=await Promise.all([supabase.functions.invoke('smspool-catalog',{body:{action:'countries'}}),supabase.functions.invoke('smspool-catalog',{body:{action:'services'}}),supabase.functions.invoke('smspool-catalog',{body:{action:'balance'}})]);if(c.error||s.error||b.error)throw new Error('Provider unavailable');const normalize=(v)=>{if(Array.isArray(v))return v;const x=v?.data??v;return Array.isArray(x)?x:Object.entries(x||{}).map(([id,name])=>({id,name}))};setCountries(normalize(c.data?.data));setServices(normalize(s.data?.data));setProviderStatus('connected')}catch{setProviderStatus('offline')}})()},[]);
 useEffect(()=>{const handler=async(event)=>{if(event.data?.type!=='litesms-payment-result')return;const d=event.data;setPaymentUrl('');setMessage(d.status==='credited'?'Deposit credited successfully.':d.status==='pending'?'Payment received; checking verification…':d.error||'Payment verification failed.');if(profile)await loadData(profile.id);if(d.status==='credited')setTab('wallet');if(d.status==='pending'&&profile){for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,2000));await loadData(profile.id)}}};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)},[profile]);
 const buyNumber=async()=>{if(Number(wallet?.balance||0)<=0){setMessage('Please add funds first.');setTab('wallet');return}setBuying(true);setMessage('');try{const t=window.Telegram?.WebApp;const {data,error}=await supabase.functions.invoke('smspool-order',{body:{initData:t?.initData,country,service}});if(error||data?.error)throw new Error(data?.error||error?.message||'Purchase failed');setMessage(`Number purchased: +${data.order.phone_number}`);await loadData(profile.id);setTab('orders')}catch(e){setMessage(e.message)}finally{setBuying(false)}};
 const startDeposit=async()=>{const n=Number(amount);if(!Number.isFinite(n)||n<100||n>1000000)return setMessage('Enter an amount between ₦100 and ₦1,000,000.');setDepositing(true);setMessage('Creating secure payment…');try{const t=window.Telegram?.WebApp;if(!t?.initData)throw new Error('Open Litesms inside Telegram.');const {data,error}=await supabase.functions.invoke('flutterwave-deposit',{body:{initData:t.initData,amount:n}});if(error||data?.error)throw new Error(data?.error||error?.message||'Could not start deposit');if(!data?.link)throw new Error('Flutterwave did not return a payment link');setPaymentUrl(data.link);setMessage('Complete your payment below.');}catch(e){setMessage(e.message)}finally{setDepositing(false)}};
 const label=(x)=>x?.name||x?.service||x?.country||x?.short_name||String(x?.id??x);const value=(x)=>x?.id??x?.code??x?.short_name??x?.name??x;
 return <main className="app"><header className="header"><div className="brand"><span className="logo">L</span><span>Litesms</span></div><div className="telegram">{authStatus}</div></header>
 {tab==='home'&&<><section className="hero"><p className="eyebrow">SMS & Phone Numbers</p><h1>{profile?.first_name?`Welcome, ${profile.first_name}`:'Everything you need, in one place.'}</h1><p className="muted">Buy virtual numbers, receive SMS and manage your balance.</p></section><section className="cards"><article><span>💳</span><p>Wallet Balance</p><strong>₦{Number(wallet?.balance||0).toLocaleString()}</strong></article><article><span>📱</span><p>Active Orders</p><strong>{orders.filter(o=>!['completed','cancelled','refunded'].includes(o.status)).length}</strong></article></section><div className={`db-status ${dbStatus}`}><span className="status-dot"/> Supabase {dbStatus}</div><div className={`db-status ${providerStatus}`}><span className="status-dot"/> SMSPool {providerStatus}</div><button className="primary" onClick={()=>setTab('buy')}>Buy a Number</button></>}
 {tab==='buy'&&<section className="panel"><h2>Buy a Number</h2><p className="muted">Live countries and services from SMSPool.</p><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}>{countries.length?countries.map((x,i)=><option key={i} value={value(x)}>{label(x)}</option>):<><option value="US">United States</option><option value="GB">United Kingdom</option><option value="NG">Nigeria</option></>}</select></label><label>Service<select value={service} onChange={e=>setService(e.target.value)}>{services.length?services.map((x,i)=><option key={i} value={value(x)}>{label(x)}</option>):<><option>Discord</option><option>Telegram</option><option>Google</option><option>WhatsApp</option><option>Instagram</option></>}</select></label><div className="notice">Provider: SMSPool · API key secured server-side</div>{message&&<div className="notice">{message}</div>}<button className="primary" disabled={buying||providerStatus!=='connected'||Number(wallet?.balance||0)<=0} onClick={buyNumber}>{buying?'Purchasing…':Number(wallet?.balance||0)<=0?'Add Funds to Purchase':providerStatus!=='connected'?'SMSPool Offline':'Purchase Number'}</button></section>}
 {tab==='orders'&&<section className="panel"><h2>Orders</h2><p className="muted">Your SMS number orders.</p>{orders.length?orders.map(o=><article className="order" key={o.id}><strong>{o.service||'SMS Service'}</strong><span>{o.phone_number||'Pending number'}</span><small>{o.status} · ${Number(o.amount||0).toFixed(2)}</small>{o.sms_code&&<b className="code">Code: {o.sms_code}</b>}</article>):<div className="empty">No orders yet.</div>}<button className="primary" onClick={()=>setTab('buy')}>Buy a Number</button></section>}
 {tab==='wallet'&&<section className="panel"><h2>Wallet</h2><div className="balance">₦{Number(wallet?.balance||0).toLocaleString()}</div><p className="muted">Available balance</p><h3>Deposit Naira</h3><div className="amounts">{['1000','5000','10000','20000','50000'].map(v=><button className="secondary" key={v} onClick={()=>setAmount(v)}>₦{Number(v).toLocaleString()}</button>)}</div><label>Amount (NGN)<input type="number" min="100" max="1000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="primary" disabled={depositing} onClick={startDeposit}>{depositing?'Creating deposit…':'Deposit with Flutterwave'}</button>{message&&<div className="notice">{message}</div>}<p className="muted">Your payment is verified by Flutterwave before your Litesms wallet is credited.</p></section>}
 {tab==='profile'&&<section className="panel"><h2>Profile</h2><div className="profile"><strong>{profile?.first_name||'Telegram User'} {profile?.last_name||''}</strong><span>@{profile?.username||'user'}</span><small>Telegram ID: {profile?.telegram_user_id||'—'}</small></div></section>}
 {paymentUrl&&<div className="payment-overlay"><div className="payment-head"><strong>Flutterwave Payment</strong><button onClick={()=>setPaymentUrl('')}>Back</button></div><iframe title="Flutterwave Payment" src={paymentUrl} className="payment-frame" /></div>}
 <nav className="bottom"><a className={tab==='home'?'active':''} onClick={()=>setTab('home')}>Home</a><a className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Orders</a><a className={tab==='wallet'?'active':''} onClick={()=>setTab('wallet')}>Wallet</a><a className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>Profile</a></nav></main>}
createRoot(document.getElementById('root')).render(<App/>);