import React,{useEffect,useMemo,useState}from'react';
import{supabase}from'./lib/supabase';
const money=n=>`₦${Number(n||0).toLocaleString('en-NG')}`;
const cleanHtml=html=>{if(!html)return'';const doc=new DOMParser().parseFromString(String(html),'text/html');const allowed=new Set(['P','BR','STRONG','B','EM','I','UL','OL','LI','SPAN']);doc.body.querySelectorAll('*').forEach(el=>{if(!allowed.has(el.tagName)){while(el.firstChild)el.parentNode?.insertBefore(el.firstChild,el);el.remove();return}for(const a of [...el.attributes])el.removeAttribute(a.name)});return doc.body.innerHTML};
const call=async(fn,body)=>{const r=await supabase.functions.invoke(fn,{body});if(r.error){let msg=r.error.message||'Edge Function request failed';try{const b=await r.error.context?.json();if(b?.error)msg=String(b.error)}catch{}return{data:r.data,error:{message:msg}}}return r};
const PAGE_SIZE=40;
const ServiceCard=({s,onOrder})=><article className="order" style={{background:'#fff'}}><details><summary style={{cursor:'pointer',fontWeight:700,fontSize:16,lineHeight:1.35}}>{s.name}</summary><div style={{marginTop:10,lineHeight:1.5}} dangerouslySetInnerHTML={{__html:cleanHtml(s.description)}}/></details><div className="order-meta"><small>Min {s.min}</small><small>Max {s.max}</small><small>{money(s.price_ngn)}/1K</small></div><button className="secondary" onClick={()=>onOrder(s)}>Order</button></article>;
export default function SmmPage(){const[services,setServices]=useState([]),[orders,setOrders]=useState([]),[category,setCategory]=useState('All'),[search,setSearch]=useState(''),[shown,setShown]=useState(PAGE_SIZE),[selected,setSelected]=useState(null),[target,setTarget]=useState(''),[quantity,setQuantity]=useState(''),[loading,setLoading]=useState(true),[buying,setBuying]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('services');
 const load=async()=>{setLoading(true);setMessage('');try{const initData=window.Telegram?.WebApp?.initData;if(!initData)throw Error('Open Litesms inside Telegram.');const r=await call('figipanel',{initData,action:'catalog'});if(r.error||r.data?.error)throw Error(r.data?.error||r.error?.message||'Unable to load services');setServices(r.data?.services||[])}catch(e){setMessage(e.message||'Unable to load SMM services.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const cats=useMemo(()=>['All',...Array.from(new Set(services.map(s=>s.category).filter(Boolean)))],[services]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return services.filter(s=>(category==='All'||s.category===category)&&(!q||`${s.name} ${s.category} ${s.description}`.toLowerCase().includes(q)))},[services,category,search]);
 useEffect(()=>setShown(PAGE_SIZE),[category,search]);
 const rendered=visible.slice(0,shown);
 const buy=async()=>{const qty=Number(quantity);if(!selected||!target.trim())return setMessage('Enter the target link.');if(!Number.isInteger(qty)||qty<selected.min||qty>selected.max)return setMessage(`Quantity must be between ${selected.min} and ${selected.max}.`);setBuying(true);setMessage('');try{const initData=window.Telegram?.WebApp?.initData;const r=await call('figipanel',{initData,action:'order',service_id:selected.id,target:target.trim(),quantity:qty,client_reference:crypto.randomUUID()});if(r.error||r.data?.error)throw Error(r.data?.error||r.error?.message||'Purchase failed');setMessage('Order placed successfully.');setTab('orders');setSelected(null);setTarget('');setQuantity('')}catch(e){setMessage(e.message||'Purchase failed')}finally{setBuying(false)}};
 return <section className="panel"><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><div><p className="eyebrow" style={{marginBottom:4}}>Social Media</p><h2 style={{margin:'0 0 4px'}}>SMM Services</h2></div><button className="secondary" onClick={()=>{window.history.pushState({},'', '/');window.dispatchEvent(new PopStateEvent('popstate'))}}>Back</button></div><div style={{display:'flex',gap:8,margin:'14px 0',overflowX:'auto'}}><button className={tab==='services'?'primary':'secondary'} style={{width:'auto',padding:'10px 14px'}} onClick={()=>setTab('services')}>Services</button><button className={tab==='orders'?'primary':'secondary'} style={{width:'auto',padding:'10px 14px'}} onClick={()=>setTab('orders')}>My Orders</button></div>{message&&<div className="notice">{message}</div>}{tab==='services'&&(loading?<div className="empty">Loading services…</div>:<><input aria-label="Search SMM services" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services…" style={{marginBottom:10}}/><div style={{display:'flex',gap:7,overflowX:'auto',paddingBottom:8}}>{cats.map(c=><button key={c} className={category===c?'primary':'secondary'} style={{width:'auto',padding:'9px 12px',whiteSpace:'nowrap'}} onClick={()=>setCategory(c)}>{c}</button>)}</div><div style={{display:'grid',gap:10}}>{rendered.map(s=><ServiceCard key={s.id} s={s} onOrder={s=>{setSelected(s);setQuantity(String(s.min));setTarget('');setMessage('')}}/>)}{shown<visible.length&&<button className="secondary" onClick={()=>setShown(v=>v+PAGE_SIZE)}>Load more ({visible.length-shown} remaining)</button>}{!visible.length&&<div className="empty">No services available.</div>}</div></>)}{tab==='orders'&&<div><div className="empty">Order history is available here after placing an order.</div></div>}{selected&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(15,23,42,.45)',display:'flex',alignItems:'flex-end',justifyContent:'center',padding:12}}><div className="panel" style={{background:'#fff',width:'100%',maxWidth:520,borderRadius:22,padding:'20px',boxShadow:'0 20px 50px rgba(0,0,0,.2)'}}><h2 style={{marginTop:0}}>{selected.name}</h2><div className="muted" style={{lineHeight:1.5,marginBottom:10}} dangerouslySetInnerHTML={{__html:cleanHtml(selected.description)}}/><label>Target / Link<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="https://…"/></label><label>Quantity<input type="number" min={selected.min} max={selected.max} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button className="primary" disabled={buying} onClick={buy}>{buying?'Processing…':'Confirm Purchase'}</button><button className="secondary" style={{width:'100%',marginTop:8,padding:13}} onClick={()=>setSelected(null)}>Close</button></div></div>}</section>}
