import React,{useDeferredValue,useEffect,useMemo,useState}from'react';
import{supabase}from'./lib/supabase';

const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:2});
const serviceLogo=(name)=>{const raw=String(name||'').trim().toLowerCase();const aliases={twitter:'x','twitter/x':'x','x/twitter':'x',bumble:'bumble'};const s=aliases[raw]||raw.replace(/[^a-z0-9]+/g,'');return s?'https://cdn.simpleicons.org/'+s:''};
const serviceFallbackLogo=(name)=>{const raw=String(name||'').trim().toLowerCase();const domains={twitter:'x.com','twitter/x':'x.com','x/twitter':'x.com',bumble:'bumble.com',whatsapp:'whatsapp.com',telegram:'telegram.org',facebook:'facebook.com',instagram:'instagram.com',tiktok:'tiktok.com',snapchat:'snapchat.com',discord:'discord.com',tinder:'tinder.com',reddit:'reddit.com',linkedin:'linkedin.com',youtube:'youtube.com',google:'google.com',amazon:'amazon.com',microsoft:'microsoft.com',apple:'apple.com',uber:'uber.com',spotify:'spotify.com',netflix:'netflix.com'};const domain=domains[raw]||raw.replace(/[^a-z0-9]+/g,'')+'.com';return 'https://www.google.com/s2/favicons?domain='+encodeURIComponent(domain)+'&sz=64'};
const platformLogo=(category,name)=>{const text=(String(category||'')+' '+String(name||'')).toLowerCase();const platforms=['instagram','tiktok','facebook','telegram','youtube','twitter','linkedin','quora','spotify','twitch','discord','snapchat','reddit','pinterest','google','soundcloud','tumblr','vimeo','vk'];const hit=platforms.find(p=>text.includes(p));return hit?serviceLogo(hit):''};
const cleanHtml=html=>{if(!html)return'';const doc=new DOMParser().parseFromString(String(html),'text/html');const allowed=new Set(['P','BR','STRONG','B','EM','I','UL','OL','LI','SPAN']);doc.body.querySelectorAll('*').forEach(el=>{if(!allowed.has(el.tagName)){while(el.firstChild)el.parentNode?.insertBefore(el.firstChild,el);el.remove();return}for(const a of [...el.attributes])el.removeAttribute(a.name)});return doc.body.innerHTML};
const call=async(fn,body)=>{const r=await supabase.functions.invoke(fn,{body});if(r.error){let msg=r.error.message||'Edge Function request failed';try{const b=await r.error.context?.json();if(b?.error)msg=String(b.error)}catch{}return{data:r.data,error:{message:msg}}}return r};

const NETWORKS=[['All',''],['Instagram','instagram'],['TikTok','tiktok'],['Facebook','facebook'],['Telegram','telegram'],['YouTube','youtube'],['Twitter','twitter'],['LinkedIn','linkedin'],['Quora','quora'],['Spotify','spotify'],['Twitch','twitch'],['Discord','discord'],['Web Traffic',''],['VK','vk'],['Snapchat','snapchat'],['Reddit','reddit'],['Pinterest','pinterest'],['Google','google'],['SoundCloud','soundcloud'],['Tumblr','tumblr'],['Vimeo','vimeo'],['Others','']];
const platformMatch=(category,name,network)=>{if(network==='All')return true;const s=String(category||'')+' '+String(name||'');if(network==='Others')return !NETWORKS.slice(1,-1).some(([n])=>s.toLowerCase().includes(n.toLowerCase()));return s.toLowerCase().includes(network.toLowerCase())};

const ServiceInfo=({service})=>service?<article className="order" style={{background:'#f8fafc',padding:16,borderRadius:16,border:'1px solid rgba(15,23,42,.06)'}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><div style={{width:48,height:48,display:"grid",placeItems:"center",flex:"0 0 auto"}}>{platformLogo(service.category,service.name)?<img src={platformLogo(service.category,service.name)} alt="" style={{width:42,height:42,objectFit:"contain"}} onError={e=>{if(e.currentTarget.dataset.fallback){e.currentTarget.style.display="none";return}e.currentTarget.dataset.fallback="1";e.currentTarget.src=serviceFallbackLogo(platformLogo(service.category,service.name).split("/").pop()||"")}}/>:<span style={{fontSize:28}}>◎</span>}</div><div style={{minWidth:0,flex:1}}><div style={{display:'inline-block',padding:'4px 7px',borderRadius:6,background:'#eef2ff',fontSize:11,fontWeight:800,color:'#334155'}}>ID: {service.id}</div><h3 style={{margin:'7px 0 10px',fontSize:15,lineHeight:1.45}}>{service.name}</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><small className="muted">Rate per 1K</small><strong style={{display:'block',color:'#2563eb'}}>{money(service.price_ngn)}</strong></div><div><small className="muted">Minimum</small><strong style={{display:'block'}}>{Number(service.min||0).toLocaleString()}</strong></div><div><small className="muted">Maximum</small><strong style={{display:'block'}}>{Number(service.max||0).toLocaleString()}</strong></div><div><small className="muted">Type</small><strong style={{display:'block'}}>{service.type||'Standard'}</strong></div></div></div></div><div style={{marginTop:14}}><strong style={{fontSize:13}}>Description</strong><div className="muted" style={{marginTop:7,lineHeight:1.55,fontSize:12}} dangerouslySetInnerHTML={{__html:cleanHtml(service.description||'No additional description available.')}}/></div></article>:null;

export default function SmmPage(){
 const[services,setServices]=useState([]),[orders,setOrders]=useState([]),[network,setNetwork]=useState('All'),[category,setCategory]=useState('All'),[search,setSearch]=useState(''),[confirmed,setConfirmed]=useState(false),[selected,setSelected]=useState(null),[target,setTarget]=useState(''),[quantity,setQuantity]=useState(''),[loading,setLoading]=useState(true),[buying,setBuying]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('single'),[favoriteIds,setFavoriteIds]=useState(()=>{try{return JSON.parse(localStorage.getItem('litesms_smm_favorites')||'[]')}catch{return[]} });
 const deferredSearch=useDeferredValue(search);

 const load=async()=>{setLoading(true);setMessage('');try{const initData=window.Telegram?.WebApp?.initData;if(!initData)throw Error('Open Litesms inside Telegram.');const r=await call('figipanel',{initData,action:'catalog'});if(r.error||r.data?.error)throw Error(r.data?.error||r.error?.message||'Unable to load services');setServices((r.data?.services||[]).map(s=>({...s,_searchText:(String(s.name||'')+' '+String(s.category||'')+' '+String(s.description||'')).toLowerCase()})))}catch(e){setMessage(e.message||'Unable to load services.')}finally{setLoading(false)}};
 const loadOrders=async()=>{try{const initData=window.Telegram?.WebApp?.initData;if(!initData)return;const r=await call('figipanel',{initData,action:'orders'});if(!r.error&&!r.data?.error)setOrders(r.data?.orders||[])}catch{}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(tab==='orders')loadOrders()},[tab]);
 useEffect(()=>{try{localStorage.setItem('litesms_smm_favorites',JSON.stringify(favoriteIds))}catch{}},[favoriteIds]);

 const networkServices=useMemo(()=>services.filter(s=>platformMatch(s.category,s.name,network)),[services,network]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return networkServices.filter(s=>(category==='All'||String(s.category||'')===category)&&(!q||s._searchText?.includes(q)))},[networkServices,category,deferredSearch]);
 const categories=useMemo(()=>Array.from(new Set(networkServices.map(s=>s.category).filter(Boolean))),[networkServices]);
 const visibleServices=useMemo(()=>filtered.length>150?filtered.slice(0,150):filtered,[filtered]);
 const serviceById=useMemo(()=>new Map(services.map(s=>[String(s.id),s])),[services]);
 const toggleFavorite=id=>setFavoriteIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const chooseService=s=>{if(!s){setSelected(null);return}setSelected(s);setQuantity(String(s.min||''));setTarget('');setConfirmed(false);setMessage('');setTab('single')};
 const charge=selected?(Number(quantity)||0)/1000*Number(selected.price_ngn||0):0;

 const buy=async()=>{const qty=Number(quantity);if(!selected||!target.trim())return setMessage('Enter the target link.');if(!Number.isInteger(qty)||qty<selected.min||qty>selected.max)return setMessage('Quantity must be between '+selected.min+' and '+selected.max+'.');setBuying(true);setMessage('');try{const initData=window.Telegram?.WebApp?.initData;const r=await call('figipanel',{initData,action:'order',service_id:selected.id,target:target.trim(),quantity:qty,client_reference:crypto.randomUUID()});if(r.error||r.data?.error)throw Error(r.data?.error||r.error?.message||'Order failed');setMessage('Order placed successfully.');setTarget('');setQuantity('');setSelected(null);setTab('orders')}catch(e){setMessage(e.message||'Order failed')}finally{setBuying(false)}};


 return <section className="panel">
  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><div><p className="eyebrow" style={{marginBottom:4}}>Social Growth</p><h2 style={{margin:0}}>Boost Accounts</h2></div><button className="secondary" onClick={()=>{window.history.pushState({},'','/');window.dispatchEvent(new PopStateEvent('popstate'))}}>Back</button></div>
  {message&&<div className="notice" style={{marginTop:12}}>{message}</div>}
  <div style={{marginTop:14,border:'1px solid rgba(15,23,42,.09)',borderRadius:18,background:'#fff',overflow:'hidden'}}>
   <div style={{padding:'16px',borderBottom:'1px solid rgba(15,23,42,.08)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong style={{fontSize:17}}>♡ Choose your preferred social network</strong><span>⌃</span></div>
   <div style={{padding:16,display:'flex',gap:8,flexWrap:'wrap'}}>{NETWORKS.map(([n,icon])=><button key={n} className={network===n?'primary':'secondary'} onClick={()=>{setNetwork(n);setCategory('All');setSearch('');setSelected(null);setConfirmed(false)}} style={{width:'auto',padding:'9px 13px',borderRadius:999,whiteSpace:'nowrap',fontSize:13}}>{icon?<img src={serviceLogo(icon)} alt="" style={{width:18,height:18,objectFit:'contain',verticalAlign:'middle',marginRight:6}} onError={e=>{if(e.currentTarget.dataset.fallback){e.currentTarget.style.display='none';return}e.currentTarget.dataset.fallback='1';e.currentTarget.src=serviceFallbackLogo(icon)}}/>:<span style={{marginRight:5,fontWeight:800}}>{n==='All'?'⌂':n==='Others'?'+':'•'}</span>}{n}</button>)}</div>
  </div>
  <div style={{marginTop:14,border:'1px solid rgba(15,23,42,.09)',borderRadius:18,background:'#fff',overflow:'hidden'}}>
   <div style={{display:'flex',borderBottom:'1px solid rgba(15,23,42,.08)',overflowX:'auto'}}><button className={tab==='single'?'primary':'secondary'} onClick={()=>setTab('single')} style={{borderRadius:0,width:'auto',padding:'11px 16px',whiteSpace:'nowrap'}}>▣ Single Order</button><button className={tab==='orders'?'primary':'secondary'} onClick={()=>setTab('orders')} style={{marginLeft:'auto',borderRadius:0,width:'auto',padding:'11px 16px',whiteSpace:'nowrap'}}>My Orders</button></div>
   {tab==='single'&&<div style={{padding:16}}>
    <h3 style={{margin:'0 0 14px',fontSize:19}}>🛒 Add new</h3>
    <label style={{display:'block',marginBottom:10}}>Search for...<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search for a service..." style={{marginTop:6}}/></label>
    <label style={{display:'block',marginBottom:10}}>Category<select value={network} onChange={e=>setNetwork(e.target.value)} style={{marginTop:6}}><option value="All">All categories</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label>
    <label style={{display:'block',marginBottom:10}}>Order Service<select value={selected?.id||''} onChange={e=>chooseService(filtered.find(s=>String(s.id)===String(e.target.value)))} style={{marginTop:6}} disabled={loading}><option value="">{loading?'Loading services...':!filtered.length?'No services found':filtered.length>150?'Search to narrow services...':'Select a service...'}</option>{visibleServices.map(s=><option key={s.id} value={s.id}>{s.id} - {s.name} - [${Number(s.rate_usd||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:6})}]</option>)}</select></label>
    {selected&&<div style={{display:'flex',justifyContent:'flex-end',marginBottom:10}}><button className="secondary" onClick={()=>toggleFavorite(selected.id)} style={{width:'auto',padding:'7px 10px'}}>{favoriteIds.includes(selected.id)?'♥ Saved':'♡ Save service'}</button></div>}
    <label style={{display:'block',marginBottom:10}}>Link<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="https://" style={{marginTop:6}}/></label>
    <label style={{display:'block',marginBottom:10}}>Quantity<input type="number" min={selected?.min||1} max={selected?.max||undefined} value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder={selected?'Enter between '+selected.min+' and '+selected.max:'Enter quantity'} style={{marginTop:6}}/></label>
    <div style={{display:'inline-flex',padding:'10px 14px',borderRadius:10,background:'#e8f5ff',color:'#1677c8',fontWeight:800,margin:'2px 0 14px'}}>Total Charge: {money(charge)}</div>
    <label style={{display:'flex',alignItems:'center',gap:9,fontSize:13,marginBottom:12}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} style={{width:20,height:20}}/>YES, I HAVE CONFIRMED THE ORDER!</label>
    <button className="primary" disabled={buying||!selected||!confirmed} onClick={buy} style={{width:'100%',padding:13}}>{buying?'Processing...':'Place order'}</button>
   </div>}
   {tab==='orders'&&<div style={{padding:16}}>{orders.length?<div style={{display:'grid',gap:10}}>{orders.map(o=>{const s=serviceById.get(String(o.service_id));const st=String(o.status||'pending').toLowerCase();const done=st==='completed',failed=st==='failed',partial=st==='partial';const label=done?'Completed':failed?'Failed':partial?'Partial':st==='processing'?'Processing':'Pending';return <article key={o.id} style={{padding:14,borderRadius:14,background:'#f8fafc'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:13}}>{s?.name||('Service #'+o.service_id)}</strong><span style={{fontSize:11,fontWeight:800}}>{label}</span></div><div style={{fontSize:12,marginTop:8}}>Quantity: {Number(o.quantity||0).toLocaleString()} · {money(o.retail_price_ngn)}</div><div style={{fontSize:12,marginTop:6,wordBreak:'break-all'}}>{o.target}</div><small className="muted">#{String(o.id).slice(0,8)} · {o.created_at?new Date(o.created_at).toLocaleString('en-NG'):''}</small></article>})}</div>:<div className="empty">No Boost Accounts orders yet.</div>}</div>}
  </div>
  {tab==='single'&&selected&&<div style={{marginTop:14}}><ServiceInfo service={selected}/></div>}
 </section>
}