import { supabase } from './lib/supabase';

const STYLE_ID='litesms-wallet-history-style';
const BOX_ID='litesms-wallet-history';
function ensureStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`#${BOX_ID}{margin:16px 0 24px;padding:16px;border-radius:16px;background:#fff;border:1px solid rgba(15,23,42,.08);box-shadow:0 4px 16px rgba(15,23,42,.05)}#${BOX_ID} .lwh-title{font-size:16px;font-weight:700;margin:0 0 12px;color:#0f172a}#${BOX_ID} .lwh-state{font-size:13px;color:#64748b;padding:10px 0}#${BOX_ID} .lwh-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-top:1px solid rgba(15,23,42,.07)}#${BOX_ID} .lwh-left{min-width:0}#${BOX_ID} .lwh-type{font-size:14px;font-weight:600;color:#0f172a}#${BOX_ID} .lwh-meta{font-size:11px;color:#64748b;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#${BOX_ID} .lwh-amount{font-size:14px;font-weight:700;white-space:nowrap}.lwh-deposit{color:#16a34a}.lwh-refund{color:#2563eb}`;document.head.appendChild(s)}
function money(v,c='NGN'){const n=Number(v);if(!Number.isFinite(n))return String(v??'');return `${c==='NGN'?'₦':c+' '}${n.toLocaleString('en-NG',{maximumFractionDigits:2})}`}function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?String(v??''):d.toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}
function getWalletPanel(){const app=document.querySelector('.app');if(!app)return null;return [...app.querySelectorAll('section.panel')].find(panel=>panel.querySelector('h2')?.textContent?.trim().toLowerCase()==='wallet')||null}
async function load(box){const tg=window.Telegram?.WebApp;box.innerHTML='<div class="lwh-title">Deposit & Refund History</div><div class="lwh-state">Loading…</div>';if(!tg?.initData){box.querySelector('.lwh-state').textContent='Open Litesms inside Telegram to view wallet history.';return}try{const {data,error}=await supabase.functions.invoke('litesms-user-data',{body:{initData:tg.initData}});if(error||data?.error)throw new Error(data?.error||error?.message||'Unable to load wallet history');const rows=(Array.isArray(data?.transactions)?data.transactions:[]).filter(x=>['deposit','refund'].includes(String(x?.type||'').toLowerCase()));box.innerHTML='<div class="lwh-title">Deposit & Refund History</div>';if(!rows.length){const e=document.createElement('div');e.className='lwh-state';e.textContent='No deposit or refund records found.';box.appendChild(e);return}rows.forEach(tx=>{const type=String(tx.type).toLowerCase();const row=document.createElement('div');row.className='lwh-row';const left=document.createElement('div');left.className='lwh-left';const title=document.createElement('div');title.className='lwh-type';title.textContent=type==='refund'?'Refund':'Deposit';const meta=document.createElement('div');meta.className='lwh-meta';meta.textContent=`${date(tx.created_at)}${tx.reference?` · ${tx.reference}`:''}`;left.append(title,meta);const amount=document.createElement('div');amount.className=`lwh-amount ${type==='refund'?'lwh-refund':'lwh-deposit'}`;amount.textContent=`+${money(tx.amount,tx.currency||'NGN')}`;row.append(left,amount);box.appendChild(row)})}catch(e){box.innerHTML='<div class="lwh-title">Deposit & Refund History</div>';const st=document.createElement('div');st.className='lwh-state';st.textContent=e?.message||'Unable to load wallet history.';box.appendChild(st)}}
function placeBox(){const panel=getWalletPanel();if(!panel)return null;let box=document.getElementById(BOX_ID);if(!box){box=document.createElement('section');box.id=BOX_ID}if(box.parentElement!==panel)panel.appendChild(box);return box}
function hideBox(){const box=document.getElementById(BOX_ID);if(box)box.remove()}
function mount(){ensureStyles();const root=document.getElementById('root');if(!root)return;const openWallet=()=>setTimeout(()=>{const box=placeBox();if(box)load(box)},0);document.addEventListener('click',e=>{const target=e.target?.closest?.('button,a,[role="button"]');if(!target)return;const text=(target.textContent||'').trim().toLowerCase();if(text==='wallet'||text.includes('wallet'))openWallet();else if(['home','orders','buy number','profile'].some(x=>text===x||text.includes(x)))hideBox()});const obs=new MutationObserver(()=>{const panel=getWalletPanel();const box=document.getElementById(BOX_ID);if(panel&&box&&box.parentElement!==panel)panel.appendChild(box);if(!panel&&box)box.remove()});obs.observe(root,{childList:true,subtree:true});if(getWalletPanel())openWallet()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();